In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Image 
from IPython.core.display import display, HTML
import pandas as pd
import numpy as np
import matplotlib as plt
from matplotlib import pyplot as plt
from datetime import datetime
import time
from tqdm import tqdm

import warnings; warnings.filterwarnings("ignore")
from matplotlib import rc
rc('font', family='Batang')
plt.rcParams['axes.unicode_minus'] = False

In [2]:
display(HTML("<style>.container { width:100% !important; }</style>"))

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 50)
pd.set_option('display.width',1000)

In [3]:
log_data = pd.read_csv("D:/data/log_data_pre.csv") # log_data에 대해서 전처리한 데이터를 사용 (결측치 대체, 행동명 매핑, 행동일시 slicing)
log_data = log_data.drop("Unnamed: 0",axis=1)

In [4]:
user_loan = pd.read_csv("D:/data/Dataset.csv")

In [5]:
log_data.head()

     유저번호                 행동명          행동명_kor                 행동일시     운영체제    앱버전          일코     년  월   일   시   분   초  운영체제_갯수
0  576409      StartLoanApply  한도조회_시작하기_버튼_클릭  2022-03-25 11:12:09  Android  3.8.2  2022-03-25  2022  3  25  11  12   9        1
1  576409  ViewLoanApplyIntro  한도조회_인트로_페이지_조회  2022-03-25 11:12:09  Android  3.8.2  2022-03-25  2022  3  25  11  12   9        1
2   72878        EndLoanApply       한도조회_결과_확인  2022-03-25 11:14:44  Android  3.8.4  2022-03-25  2022  3  25  11  14  44        1
3  645317             OpenApp             앱_실행  2022-03-25 11:15:09      iOS  3.6.1  2022-03-25  2022  3  25  11  15   9        2
4  645317       UseLoanManage      대출관리_서비스_이용  2022-03-25 11:15:11      iOS  3.6.1  2022-03-25  2022  3  25  11  15  11        2

In [6]:
user_loan.head()

    신청서 번호  금융사 번호  상품 번호  신청 여부(타겟)     유저 번호                 생성일시 주거소유형태  대출목적  연령대  추천 수  승인금리        승인한도  근속월수(로그)  연소득(boxcox)  신용점수(보완)   시간차(로그)  대출희망금액(boxcox)  기대출수(로그)  상품 누적 추천 수(로그)  조회 횟수(로그)
0  1748340       7    191        NaN  430982.0  2022-06-07 13:05:39     자가  대환대출  20대    35  13.6  42000000.0  1.609438     -0.70697     620.0  5.831882       -0.011204  1.098612        0.693147   2.079442
1  1748340      25    169        NaN  430982.0  2022-06-07 13:05:39     자가  대환대출  20대    35  17.9  24000000.0  1.609438     -0.70697     620.0  5.831882       -0.011204  1.098612        0.693147   2.079442
2  1748340       2      7        NaN  430982.0  2022-06-07 13:05:39     자가  대환대출  20대    35  18.5  24000000.0  1.609438     -0.70697     620.0  5.831882       -0.011204  1.098612        0.693147   2.079442
3  1748340       4    268        NaN  430982.0  2022-06-07 13:05:39     자가  대환대출  20대    35  10.8  29000000.0  1.609438     -0.70697     620.0  5.831882       -0.011204  1.098612        0.693147   2.079442
4  1748340      11    118        NaN  430982.0  2022-06-07 13:05:39     자가  대환대출  20대    35  16.4   5000000.0  1.609438     -0.70697     620.0  5.831882       -0.011204  1.098612        1.945910   2.079442

In [7]:
print(log_data.columns)
print(user_loan.columns)

Index(['유저번호', '행동명', '행동명_kor', '행동일시', '운영체제', '앱버전', '일코', '년', '월', '일', '시', '분', '초', '운영체제_갯수'], dtype='object')
Index(['신청서 번호', '금융사 번호', '상품 번호', '신청 여부(타겟)', '유저 번호', '생성일시', '주거소유형태', '대출목적', '연령대', '추천 수', '승인금리', '승인한도', '근속월수(로그)', '연소득(boxcox)', '신용점수(보완)', '시간차(로그)', '대출희망금액(boxcox)', '기대출수(로그)', '상품 누적 추천 수(로그)', '조회 횟수(로그)'], dtype='object')

In [8]:
# loan_result 에서 신청_여부 nan 값인 6월 제거
loan_result_t = user_loan.dropna( subset=['신청 여부(타겟)'] )
loan_result_t.isnull().sum()

신청서 번호            0
금융사 번호            0
상품 번호             0
신청 여부(타겟)         0
유저 번호             0
생성일시              0
주거소유형태            0
대출목적              0
연령대               0
추천 수              0
승인금리              0
승인한도              0
근속월수(로그)          0
연소득(boxcox)       0
신용점수(보완)          0
시간차(로그)           0
대출희망금액(boxcox)    0
기대출수(로그)          0
상품 누적 추천 수(로그)    0
조회 횟수(로그)         0
dtype: int64